#!/bin/bash

export SIMPLEWEBAPP__COMMON__NAME="Overwritten Application Name"

export SIMPLEWEBAPP__COMMON__DEBUG="FALSE"


export SIMPLEWEBAPP__COMMON__DATE="$(date)"
export SIMPLEWEBAPP__COMMON__SECRET__KEY="seckey"
export SIMPLEWEBAPP__COMMON__SECRET__MAGIC="42"
export SIMPLEWEBAPP__DATABASE__CREDENTIALS__PASS="supersecretdbpass"
